.TH "basic_interrupts_lock" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_interrupts_lock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mn_critical\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBlock\fP ()"
.br
.ti -1c
.RI "virtual void \fBunlock\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper class to use the interrupts lock with autolock guard see auto_interrupt_t 
.SH "Member Function Documentation"
.PP 
.SS "virtual void basic_interrupts_lock::lock ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void basic_interrupts_lock::unlock ()\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
