.TH "basic_binary_semaphore" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_binary_semaphore
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mn_semaphore\&.hpp>\fP
.PP
Inherits \fBbasic_semaphore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic_binary_semaphore\fP ()"
.br
.ti -1c
.RI "virtual int \fBcreate\fP ()"
.br
.ti -1c
.RI "virtual int \fBdestroy\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "basic_binary_semaphore::basic_binary_semaphore ()"

.SH "Member Function Documentation"
.PP 
.SS "int basic_binary_semaphore::create ()\fC [virtual]\fP"
Create the binary semaphore 
.br
.PP
\fBReturns\fP
.RS 4
'ERR_SPINLOCK_OK' the mutex are created, 'ERR_SPINLOCK_ALREADYINIT' the mutex are already created, 'ERR_SPINLOCK_BAD_INITIALCOUNT' when the initial count greater than maxcount is and 'ERR_SPINLOCK_CANTCREATEMUTEX' on error\&. 
.RE
.PP

.SS "int basic_binary_semaphore::destroy ()\fC [virtual]\fP"
Destroyed the binary semaphore
.PP
\fBReturns\fP
.RS 4
'ERR_SPINLOCK_OK' the mutex are destroyed or ERR_SPINLOCK_NOTINIT when mutex not created 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
