.TH "libmnVersion" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmnVersion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mn_version\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~libmnVersion\fP ()"
.br
.ti -1c
.RI "int \fBget_major_version\fP () const"
.br
.ti -1c
.RI "int \fBget_minor_version\fP () const"
.br
.ti -1c
.RI "int \fBget_debug_version\fP () const"
.br
.ti -1c
.RI "std::string \fBget_license\fP () const"
.br
.ti -1c
.RI "std::string \fBto_string\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBlibmnVersion\fP & \fBinstance\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBlibmnVersion\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_license\fP"
.br
.ti -1c
.RI "int \fBm_major\fP"
.br
.ti -1c
.RI "int \fBm_minor\fP"
.br
.ti -1c
.RI "int \fBm_debug\fP"
.br
.ti -1c
.RI "std::string \fBm_extras\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBlibmnVersion\fP * \fBm_pInstance\fP = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is part of the Mini Thread Library (https://github.com/RoseLeBlood/MiniThread )\&. Copyright (c) 2018 Amber-Sophia Schroeck
.PP
The Mini Thread Library is free software; you can redistribute it and/or modify 
.br
 it under the terms of the GNU Lesser General Public License as published by 
.br
 the Free Software Foundation, version 3, or (at your option) any later version\&.
.PP
The Mini Thread Library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the Mini Thread Library; if not, see https://www.gnu.org/licenses/\&. 
.br
 Version wrapper for this library 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "libmnVersion::libmnVersion ()\fC [private]\fP"

.SS "libmnVersion::~libmnVersion ()"

.SH "Member Function Documentation"
.PP 
.SS "int libmnVersion::get_debug_version () const\fC [inline]\fP"
Get the debug version 
.PP
\fBReturns\fP
.RS 4
The debug version 
.RE
.PP

.SS "std::string libmnVersion::get_license () const\fC [inline]\fP"
Get the license string 
.PP
\fBReturns\fP
.RS 4
The license string 
.RE
.PP

.SS "int libmnVersion::get_major_version () const\fC [inline]\fP"
Get the major version 
.PP
\fBReturns\fP
.RS 4
The major version 
.RE
.PP

.SS "int libmnVersion::get_minor_version () const\fC [inline]\fP"
Get the minor version 
.PP
\fBReturns\fP
.RS 4
The minor version 
.RE
.PP

.SS "static \fBlibmnVersion\fP& libmnVersion::instance ()\fC [inline]\fP, \fC [static]\fP"
Get the singleton instances from this class 
.PP
\fBReturns\fP
.RS 4
The singleton instance 
.RE
.PP

.SS "std::string libmnVersion::to_string () const"
Get the version string with extra informations 
.PP
\fBReturns\fP
.RS 4
The version string with extra informations 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int libmnVersion::m_debug\fC [private]\fP"

.SS "std::string libmnVersion::m_extras\fC [private]\fP"
The extra versions infomations string holder 
.SS "std::string libmnVersion::m_license\fC [private]\fP"
The license string holder 
.SS "int libmnVersion::m_major\fC [private]\fP"
The Version holders 
.SS "int libmnVersion::m_minor\fC [private]\fP"

.SS "\fBlibmnVersion\fP * libmnVersion::m_pInstance = NULL\fC [static]\fP, \fC [private]\fP"
The Sigleton Object holder
.PP
This file is part of the Mini Thread Library (https://github.com/RoseLeBlood/MiniThread )\&. Copyright (c) 2018 Amber-Sophia Schroeck
.PP
The Mini Thread Library is free software; you can redistribute it and/or modify 
.br
 it under the terms of the GNU Lesser General Public License as published by 
.br
 the Free Software Foundation, version 3, or (at your option) any later version\&.
.PP
The Mini Thread Library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the Mini Thread Library; if not, see https://www.gnu.org/licenses/\&. 
.br
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
