.TH "md__home_ambersophia__dokumente_git_mnthread__change_log" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_ambersophia__dokumente_git_mnthread__change_log \- Changelog 
Version 1\&.60 September 2020: (unstable nightly)
.IP "\(bu" 2
add Work queue support (\fBbasic_work_queue\fP) Create one or more \fBbasic_work_queue\fP to accept \fBwork_queue_item\fP\&. \fBbasic_work_queue\fP pull \fBwork_queue_item\fP off of a FIFO queue and run them sequentially\&. 
.br

.IP "\(bu" 2
add New Config Options to mn_conig\&.hpp
.IP "  \(bu" 4
MN_THREAD_CONFIG_WORK_QUEUE_MAX_WORK_ITEMS: How many work items to queue in the work queue engine default is 8
.IP "  \(bu" 4
MN_THREAD_CONFIG_WORK_QUEUE_STACK_SIZE: Default Stak size for the work queue thread\&. defaultis (configMINIMAL_STACK_SIZE * 2)
.IP "  \(bu" 4
MN_THREAD_CONFIG_WORK_QUEUE_PRIORITY Default Priority for the work queue thread\&. default is (tskIDLE_PRIORITY + 1)
.IP "  \(bu" 4
MN_THREAD_CONFIG_DEFAULT_CORE Default Core to run a new Task (default MN_THREAD_CONFIG_CORE_NO)
.IP "  \(bu" 4
MN_THREAD_CONFIG_DEFAULT_WORKQUEUE_CORE On whith core run all Workques an default cas be override in the create function (default MN_THREAD_CONFIG_CORE2_TWO)
.IP "  \(bu" 4
MN_THREAD_CONFIG_LOCK_TYPE This Property change now the Autolock type and the basic LockType_t (default MN_THREAD_CONFIG_BINARY_SEMAPHORE)
.PP

.IP "\(bu" 2
remane LIB_CPU_0 -> MN_THREAD_CONFIG_CORE2_ONE and LIBMN_CPU_1 -> MN_THREAD_CONFIG_CORE2_TWO
.IP "\(bu" 2
rename libmn_panic to mn_panic
.IP "\(bu" 2
add default informations to the config file
.IP "\(bu" 2
remove config option MN_THREAD_CONFIG_MUTEX_CLASS\&. MN_THREAD_CONFIG_MUTEX_CLASS
.IP "\(bu" 2
rename libmn\&.hpp to \fBmn_base\&.hpp\fP and add missing headers
.IP "\(bu" 2
rename mn_spinlock\&.hpp => \fBmn_semaphore\&.hpp\fP and mn_spinlock\&.cpp => \fBmn_semaphore\&.cpp\fP
.IP "\(bu" 2
\fBbasic_mutex\fP extends \fBbasic_semaphore\fP
.IP "\(bu" 2
add a blocking queue, start emply a Threahpool and memory mamagment classes
.PP
.PP
Version 1\&.54 September 2020: (unstable)
.IP "\(bu" 2
Documentation ready
.IP "\(bu" 2
add Licence text to source files
.IP "\(bu" 2
remove semaphore_t and spinlock_t
.IP "\(bu" 2
add counting_semaphore_t (autocsemp_t) and binary_semaphore_t (autobinsemp_t) 
.br
 please update code semaphore_t = counting_semaphore_t, spinlock_t = binary_semaphore_t
.PP
.PP
Version 1\&.53 September 2020:
.IP "\(bu" 2
add eaxample
.IP "\(bu" 2
add Documentation add (https://roseleblood.github.io/mnthread-docs/)
.IP "\(bu" 2
rename Project from mnthread to Mini Thread
.PP
.PP
Version 1\&.43 September 2020: (stable)
.IP "\(bu" 2
move convar function from \fBbasic_thread\fP to basic_convar_thread
.IP "\(bu" 2
add basic_convar_thread when 'MN_THREAD_CONFIG_CONDITION_VARIABLE_SUPPORT  MN_THREAD_CONFIG_YES'is and update basic_condition_variable
.IP "\(bu" 2
remove errors - (sorry, \&.\&.\&. )
.IP "\(bu" 2
add a deque class that implements a double ended queue\&. (deque_t = \fBbasic_deque\fP)
.PP
.PP
Version 1\&.42 August 2020: (non-stable)
.IP "\(bu" 2
add queue wrapper (\fBqueue/mn_queue\&.hpp\fP) queue_t
.IP "\(bu" 2
add binary queue (\fBqueue/mn_binaryqueue\&.hpp\fP) binaryqueue_t
.PP
.PP
Version 1\&.4 August 2020: (non-stable)
.IP "\(bu" 2
add Conditional Variable an disable in config file (\fBmn_config\&.hpp\fP)
.IP "\(bu" 2
add new Cosfigurations items on \fBmn_config\&.hpp\fP
.IP "\(bu" 2
add recursive matux and autolack tps for interrupt, critical_lock and schedular
.IP "\(bu" 2
add Tasklets
.PP
.PP
Version 1\&.2 August 2020: (stable)
.IP "\(bu" 2
rename the header files from mn-(xxx)\&.h to mn_(xxx)\&.hpp
.IP "\(bu" 2
Platformio regestration
.PP
.PP
Version 1\&.0\&.62 Mai 2020: (non-stable)
.IP "\(bu" 2
update examples - stripped
.IP "\(bu" 2
switch from c3pb\&.gitlab to my public github account
.PP
.PP
Version 1\&.0\&.60 November 2018: (non-stable)
.IP "\(bu" 2
rename:
.IP "  \(bu" 4
sleep -> mn_sleep
.IP "  \(bu" 4
usleep -> mn_usleep
.IP "  \(bu" 4
nsleep -> mn_nsleep
.PP

.IP "\(bu" 2
start thread mutext unlock funktion - see examples
.IP "\(bu" 2
update examples
.IP "\(bu" 2
update version Version 1\&.0\&.5 November 2018: (stable)
.IP "\(bu" 2
Add libmn\&.h
.IP "\(bu" 2
Add Config : mn-config\&.h
.IP "\(bu" 2
rename header
.IP "\(bu" 2
Add examples
.PP
.PP
Version 0\&.9\&.3 November 2018: (non-stable)
.IP "\(bu" 2
add autolock_t to mn-Thread
.IP "\(bu" 2
add mn-autolock\&.h
.IP "\(bu" 2
add spinlock
.PP
.PP
Version 0\&.8\&.31 November 2018: (non-stable)
.IP "\(bu" 2
add logical mutext handle to \fBbasic_thread\fP
.IP "\(bu" 2
rename function 'delay' to 'sleep' in \fBbasic_thread\fP
.IP "\(bu" 2
add function 'nsleep' and 'usleep' to \fBbasic_thread\fP
.IP "\(bu" 2
add 'child_thread' and 'parent_thread' to \fBbasic_thread\fP
.IP "\(bu" 2
add function 'get_root();' 'get_child();' 'add_child_thread(basic_thread* thread);'
.PP
.PP
Version 0\&.8\&.3 November 2018: (non-stable)
.IP "\(bu" 2
add nsleep, sleep, usleep, micros, milis
.PP
.PP
Version 0\&.8\&.2, November 2018: (non-stable)
.IP "\(bu" 2
Public release 
.PP

