.TH "mn_base.hpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_base.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'freertos/FreeRTOS\&.h'\fP
.br
\fC#include 'freertos/semphr\&.h'\fP
.br
\fC#include 'freertos/task\&.h'\fP
.br
\fC#include 'freertos/queue\&.h'\fP
.br
\fC#include 'mn_config\&.hpp'\fP
.br
\fC#include 'mn_version\&.hpp'\fP
.br
\fC#include 'mn_autolock\&.hpp'\fP
.br
\fC#include 'mn_micros\&.hpp'\fP
.br
\fC#include 'mn_thread\&.hpp'\fP
.br
\fC#include 'mn_convar\&.hpp'\fP
.br
\fC#include 'mn_convar_thread\&.hpp'\fP
.br
\fC#include 'queue/mn_queue\&.hpp'\fP
.br
\fC#include 'queue/mn_binaryqueue\&.hpp'\fP
.br
\fC#include 'queue/mn_deque\&.hpp'\fP
.br
\fC#include 'queue/mn_workqueue\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmn_panic\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mn_panic ()"
This file is part of the Mini Thread Library (https://github.com/RoseLeBlood/MiniThread )\&. Copyright (c) 2018 Amber-Sophia Schroeck
.PP
The Mini Thread Library is free software; you can redistribute it and/or modify 
.br
 it under the terms of the GNU Lesser General Public License as published by 
.br
 the Free Software Foundation, version 3, or (at your option) any later version\&.
.PP
The Mini Thread Library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the Mini Thread Library; if not, see https://www.gnu.org/licenses/\&. 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
