.TH "mn_blocking_queue.cpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_blocking_queue.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'freertos/FreeRTOS\&.h'\fP
.br
\fC#include 'freertos/queue\&.h'\fP
.br
\fC#include 'queue/mn_blocking_queue\&.hpp'\fP
.br
\fC#include 'mn_error\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
