.TH "mn_config.hpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_config.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'freertos/FreeRTOS\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMN_THREAD_MAJOR_VERSION\fP   1"
.br
.ti -1c
.RI "#define \fBMN_THREAD_MINOR_VERSION\fP   6"
.br
.ti -1c
.RI "#define \fBMN_THREAD_DEBUG_VERSION\fP   0"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_MUTEX\fP   1"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_COUNTING_SEMAPHORE\fP   2"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_BINARY_SEMAPHORE\fP   3"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_YES\fP   1"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_NO\fP   2"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_CORE_NO\fP   \-1"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_CORE_ONE\fP   0"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_CORE2_TWO\fP   1"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_MAX_CPUS\fP   2"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_DEFAULT_CORE\fP   \fBMN_THREAD_CONFIG_CORE_NO\fP"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_DEFAULT_WORKQUEUE_CORE\fP   \fBMN_THREAD_CONFIG_CORE2_TWO\fP"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_LOCK_TYPE\fP   \fBMN_THREAD_CONFIG_BINARY_SEMAPHORE\fP"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_CONDITION_VARIABLE_SUPPORT\fP   \fBMN_THREAD_CONFIG_YES\fP"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_WORK_QUEUE_MAX_WORK_ITEMS\fP   8"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_WORK_QUEUE_STACK_SIZE\fP   (configMINIMAL_STACK_SIZE * 2)"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_WORK_QUEUE_PRIORITY\fP   (tskIDLE_PRIORITY + 1)"
.br
.ti -1c
.RI "#define \fBMN_THREAD_CONFIG_RECURSIVE_MUTEX\fP   \fBMN_THREAD_CONFIG_YES\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MN_THREAD_CONFIG_BINARY_SEMAPHORE   3"

.SS "#define MN_THREAD_CONFIG_CONDITION_VARIABLE_SUPPORT   \fBMN_THREAD_CONFIG_YES\fP"
Condition variable support for this libary 'MN_THREAD_CONFIG_YES' or 'MN_THREAD_CONFIG_NO' default: MN_THREAD_CONFIG_YES 
.SS "#define MN_THREAD_CONFIG_CORE2_TWO   1"

.SS "#define MN_THREAD_CONFIG_CORE_NO   \-1"

.SS "#define MN_THREAD_CONFIG_CORE_ONE   0"

.SS "#define MN_THREAD_CONFIG_COUNTING_SEMAPHORE   2"

.SS "#define MN_THREAD_CONFIG_DEFAULT_CORE   \fBMN_THREAD_CONFIG_CORE_NO\fP"

.SS "#define MN_THREAD_CONFIG_DEFAULT_WORKQUEUE_CORE   \fBMN_THREAD_CONFIG_CORE2_TWO\fP"

.SS "#define MN_THREAD_CONFIG_LOCK_TYPE   \fBMN_THREAD_CONFIG_BINARY_SEMAPHORE\fP"
Default lock type using in the thread class MN_THREAD_CONFIG_MUTEX: using the mutex as default lock type MN_THREAD_CONFIG_BINARY_SEMAPHORE using the binary semaphore as default lock type MN_THREAD_CONFIG_COUNTING_SEMAPHORE: using the counting semaphore as default lock type default: MN_THREAD_CONFIG_BINARY_SEMAPHORE 
.SS "#define MN_THREAD_CONFIG_MAX_CPUS   2"

.SS "#define MN_THREAD_CONFIG_MUTEX   1"

.SS "#define MN_THREAD_CONFIG_NO   2"

.SS "#define MN_THREAD_CONFIG_RECURSIVE_MUTEX   \fBMN_THREAD_CONFIG_YES\fP"

.SH "Ab hier nichts verändern | DO NOT EDIT AFTER THIS LINE!!!"
.PP
Supported the FeeRTOS RECURSIVE_MUTEXES ? 
.PP
\fBNote\fP
.RS 4
Don't edit Enabled Build with RECURSIVE_MUTEXES support 
.RE
.PP

.SS "#define MN_THREAD_CONFIG_WORK_QUEUE_MAX_WORK_ITEMS   8"
How many work items to queue in the work queue engine default: 8 
.SS "#define MN_THREAD_CONFIG_WORK_QUEUE_PRIORITY   (tskIDLE_PRIORITY + 1)"
Default Priority for the work queue thread default: (tskIDLE_PRIORITY + 1) 
.SS "#define MN_THREAD_CONFIG_WORK_QUEUE_STACK_SIZE   (configMINIMAL_STACK_SIZE * 2)"
Stak size for the work queue thread default: (configMINIMAL_STACK_SIZE * 2) 
.SS "#define MN_THREAD_CONFIG_YES   1"

.SS "#define MN_THREAD_DEBUG_VERSION   0"

.SS "#define MN_THREAD_MAJOR_VERSION   1"
This file is part of the Mini Thread Library (https://github.com/RoseLeBlood/MiniThread )\&. Copyright (c) 2018 Amber-Sophia Schroeck
.PP
The Mini Thread Library is free software; you can redistribute it and/or modify 
.br
 it under the terms of the GNU Lesser General Public License as published by 
.br
 the Free Software Foundation, version 3, or (at your option) any later version\&.
.PP
The Mini Thread Library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the Mini Thread Library; if not, see https://www.gnu.org/licenses/\&. 
.br
 
.SS "#define MN_THREAD_MINOR_VERSION   6"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
