.TH "mn_critical.hpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_critical.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mn_mutex\&.hpp'\fP
.br
\fC#include 'freertos/FreeRTOS\&.h'\fP
.br
\fC#include 'freertos/task\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbasic_critical\fP"
.br
.ti -1c
.RI "class \fBbasic_critical_lock\fP"
.br
.ti -1c
.RI "class \fBbasic_interrupts_lock\fP"
.br
.ti -1c
.RI "class \fBbasic_scheduler_lock\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcritical_t\fP = \fBbasic_critical\fP"
.br
.ti -1c
.RI "using \fBcritical_lock_t\fP = \fBbasic_critical_lock\fP"
.br
.ti -1c
.RI "using \fBinterrupts_lock_t\fP = \fBbasic_interrupts_lock\fP"
.br
.ti -1c
.RI "using \fBsheduler_lock_t\fP = \fBbasic_scheduler_lock\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBcritical_lock_t\fP =  \fBbasic_critical_lock\fP"

.SS "using \fBcritical_t\fP =  \fBbasic_critical\fP"

.SS "using \fBinterrupts_lock_t\fP =  \fBbasic_interrupts_lock\fP"

.SS "using \fBsheduler_lock_t\fP =  \fBbasic_scheduler_lock\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
