.TH "mn_error.hpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_error.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNO_ERROR\fP   0"
.br
.ti -1c
.RI "#define \fBERR_MUTEX_OK\fP   \fBNO_ERROR\fP"
.br
.ti -1c
.RI "#define \fBERR_MUTEX_ALREADYINIT\fP   \-1"
.br
.ti -1c
.RI "#define \fBERR_MUTEX_NOTINIT\fP   \-2"
.br
.ti -1c
.RI "#define \fBERR_MUTEX_CANTCREATEMUTEX\fP   \-3"
.br
.ti -1c
.RI "#define \fBERR_MUTEX_LOCK\fP   \-4"
.br
.ti -1c
.RI "#define \fBERR_MUTEX_UNLOCK\fP   \-5"
.br
.ti -1c
.RI "#define \fBERR_SPINLOCK_OK\fP   \fBNO_ERROR\fP"
.br
.ti -1c
.RI "#define \fBERR_SPINLOCK_ALREADYINIT\fP   \-1"
.br
.ti -1c
.RI "#define \fBERR_SPINLOCK_NOTINIT\fP   \-2"
.br
.ti -1c
.RI "#define \fBERR_SPINLOCK_CANTCREATESPINLOCK\fP   \-3"
.br
.ti -1c
.RI "#define \fBERR_SPINLOCK_LOCK\fP   \-4"
.br
.ti -1c
.RI "#define \fBERR_SPINLOCK_UNLOCK\fP   \-5"
.br
.ti -1c
.RI "#define \fBERR_SPINLOCK_BAD_INITIALCOUNT\fP   \-6"
.br
.ti -1c
.RI "#define \fBERR_THREAD_OK\fP   \fBNO_ERROR\fP"
.br
.ti -1c
.RI "#define \fBERR_THREAD_CANTINITMUTEX\fP   \-4"
.br
.ti -1c
.RI "#define \fBERR_THREAD_CANTSTARTTHREAD\fP   \-5"
.br
.ti -1c
.RI "#define \fBERR_THREAD_THREADFUNCNOTSET\fP   \-6"
.br
.ti -1c
.RI "#define \fBERR_THREAD_NOTRUNNING\fP   \-7"
.br
.ti -1c
.RI "#define \fBERR_THREAD_ALREADYRUNNING\fP   \-8"
.br
.ti -1c
.RI "#define \fBERR_TASKLET_OK\fP   \fBNO_ERROR\fP"
.br
.ti -1c
.RI "#define \fBERR_TASKLET_CANTINITLOCKT\fP   \-4"
.br
.ti -1c
.RI "#define \fBERR_TASKLET_CANTSTART\fP   \-5"
.br
.ti -1c
.RI "#define \fBERR_QUEUE_OK\fP   \fBNO_ERROR\fP"
.br
.ti -1c
.RI "#define \fBERR_QUEUE_ALREADYINIT\fP   \-1"
.br
.ti -1c
.RI "#define \fBERR_QUEUE_CANTCREATE\fP   \-2"
.br
.ti -1c
.RI "#define \fBERR_QUEUE_NOTCREATED\fP   \-3"
.br
.ti -1c
.RI "#define \fBERR_QUEUE_ADD\fP   \-4"
.br
.ti -1c
.RI "#define \fBERR_QUEUE_REMOVE\fP   \-5"
.br
.ti -1c
.RI "#define \fBERR_QUEUE_PEEK\fP   \-6"
.br
.ti -1c
.RI "#define \fBERR_QUEUE_CANTCREATE_LOCK\fP   \-99"
.br
.ti -1c
.RI "#define \fBERR_TIMER_OK\fP   \fBNO_ERROR\fP"
.br
.ti -1c
.RI "#define \fBERR_TIMER_ALREADYINIT\fP   \-1"
.br
.ti -1c
.RI "#define \fBERR_TIMER_CANTCREATE\fP   \-2"
.br
.ti -1c
.RI "#define \fBERR_TIMER_NOTCREATED\fP   \-3"
.br
.ti -1c
.RI "#define \fBERR_TIMER_AKTIVATE\fP   \-4"
.br
.ti -1c
.RI "#define \fBERR_TIMER_INAKTIVATE\fP   \-4"
.br
.ti -1c
.RI "#define \fBERR_TIMER_RESET\fP   \-4"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERR_MUTEX_ALREADYINIT   \-1"
The mutex allready created 
.SS "#define ERR_MUTEX_CANTCREATEMUTEX   \-3"
The mutex can't create 
.SS "#define ERR_MUTEX_LOCK   \-4"
It timed out on lock the mutex - mutex are not locked 
.SS "#define ERR_MUTEX_NOTINIT   \-2"
The mutex is not created, please call create first 
.SS "#define ERR_MUTEX_OK   \fBNO_ERROR\fP"
No Error in one of the mutex function 
.SS "#define ERR_MUTEX_UNLOCK   \-5"
Error to unlock the mutex, call lock first 
.SS "#define ERR_QUEUE_ADD   \-4"
The item can not enqueued in the queue 
.SS "#define ERR_QUEUE_ALREADYINIT   \-1"
The queue is allready Created 
.SS "#define ERR_QUEUE_CANTCREATE   \-2"
The queue can't created 
.SS "#define ERR_QUEUE_CANTCREATE_LOCK   \-99"
Can not create the lock object for the blocking queue 
.SS "#define ERR_QUEUE_NOTCREATED   \-3"
The queue is not created 
.SS "#define ERR_QUEUE_OK   \fBNO_ERROR\fP"
No Error in one of the Queue function 
.SS "#define ERR_QUEUE_PEEK   \-6"
No items in the queue 
.SS "#define ERR_QUEUE_REMOVE   \-5"
The item can not remove from the queue 
.SS "#define ERR_SPINLOCK_ALREADYINIT   \-1"
The spinlock or semaphore allready created 
.SS "#define ERR_SPINLOCK_BAD_INITIALCOUNT   \-6"
Count is bigger are the max count - spinlock not created 
.SS "#define ERR_SPINLOCK_CANTCREATESPINLOCK   \-3"
The spinlock or semaphore can't create 
.SS "#define ERR_SPINLOCK_LOCK   \-4"
It timed out on lock the spinlock or semaphore - spinlock or semaphore are not locked 
.SS "#define ERR_SPINLOCK_NOTINIT   \-2"
The spinlock or semaphore is not created, please call create first 
.SS "#define ERR_SPINLOCK_OK   \fBNO_ERROR\fP"
No Error in one of the spinlock or semaphore function 
.SS "#define ERR_SPINLOCK_UNLOCK   \-5"
Error to unlock the spinlock or semaphore, call lock first 
.SS "#define ERR_TASKLET_CANTINITLOCKT   \-4"
Can not create the lock object for the tasklet, tasklet not created 
.SS "#define ERR_TASKLET_CANTSTART   \-5"
Tasklet can not created 
.SS "#define ERR_TASKLET_OK   \fBNO_ERROR\fP"
No Error in one of the Tasklet function 
.SS "#define ERR_THREAD_ALREADYRUNNING   \-8"
The thread can not start, becourse the thread is allready started 
.SS "#define ERR_THREAD_CANTINITMUTEX   \-4"
The Lock objects are maked error 
.SS "#define ERR_THREAD_CANTSTARTTHREAD   \-5"
The thread (i\&.e\&. task) can not start unknown error 
.SS "#define ERR_THREAD_NOTRUNNING   \-7"
The thread is not running 
.SS "#define ERR_THREAD_OK   \fBNO_ERROR\fP"
No Error in one of the Thread function 
.SS "#define ERR_THREAD_THREADFUNCNOTSET   \-6"
The threah function is null 
.SS "#define ERR_TIMER_AKTIVATE   \-4"
The timer can not start 
.SS "#define ERR_TIMER_ALREADYINIT   \-1"
The timer is allready Created 
.SS "#define ERR_TIMER_CANTCREATE   \-2"
The timer can't created 
.SS "#define ERR_TIMER_INAKTIVATE   \-4"
The timer can not stop 
.SS "#define ERR_TIMER_NOTCREATED   \-3"
The timer is not created 
.SS "#define ERR_TIMER_OK   \fBNO_ERROR\fP"
No Error in one of the Timer function 
.SS "#define ERR_TIMER_RESET   \-4"
The timer can not reset 
.SS "#define NO_ERROR   0"
This file is part of the Mini Thread Library (https://github.com/RoseLeBlood/MiniThread )\&. Copyright (c) 2018 Amber-Sophia Schroeck
.PP
The Mini Thread Library is free software; you can redistribute it and/or modify 
.br
 it under the terms of the GNU Lesser General Public License as published by 
.br
 the Free Software Foundation, version 3, or (at your option) any later version\&.
.PP
The Mini Thread Library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the Mini Thread Library; if not, see https://www.gnu.org/licenses/\&. 
.br
 No Error 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
