.TH "mn_semaphore.cpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_semaphore.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mn_semaphore\&.hpp'\fP
.br
\fC#include 'mn_error\&.hpp'\fP
.br
\fC#include 'freertos/FreeRTOS\&.h'\fP
.br
\fC#include 'freertos/semphr\&.h'\fP
.br
\fC#include 'freertos/queue\&.h'\fP
.br
\fC#include 'freertos/task\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'esp_attr\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
