.TH "mn_semaphore.hpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_semaphore.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mn_error\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbasic_semaphore\fP"
.br
.ti -1c
.RI "class \fBbasic_counting_semaphore\fP"
.br
.ti -1c
.RI "class \fBbasic_binary_semaphore\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcounting_semaphore_t\fP = \fBbasic_counting_semaphore\fP"
.br
.ti -1c
.RI "using \fBbinary_semaphore_t\fP = \fBbasic_binary_semaphore\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBbinary_semaphore_t\fP =  \fBbasic_binary_semaphore\fP"

.SS "using \fBcounting_semaphore_t\fP =  \fBbasic_counting_semaphore\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
