.TH "mn_thread.cpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_thread.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mn_thread\&.hpp'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fB__internal_id_base__\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "uint32_t __internal_id_base__ = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
