.TH "mn_timer.hpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_timer.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbasic_timer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBmtimer_t\fP = \fBbasic_timer\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBmtimer_t\fP =  \fBbasic_timer\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
