.TH "mn_workqueue.hpp" 3 "Tue Sep 15 2020" "Version 1.6x" "Mini Thread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mn_workqueue.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mn_workqueue_item\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbasic_work_queue\fP"
.br
.ti -1c
.RI "class \fBbasic_work_queue::work_queue_thread\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBwork_queue_t\fP = \fBbasic_work_queue\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBwork_queue_t\fP =  \fBbasic_work_queue\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mini Thread from the source code\&.
